import {
  IonApp,
  IonButton,
  IonButtons,
  IonInput,
  IonItem,
  IonLabel,
  IonList,
  IonListHeader,   // 👈 falta este
  IonContent,
  IonHeader,
  IonTitle,
  IonToolbar,
  IonCard,
  IonCardHeader,
  IonCardTitle,
  IonCardContent,
  IonIcon,
  IonGrid,
  IonRow,
  IonCol,
  IonNote,
  IonSelect,
  IonSelectOption,
  IonMenuButton,
  IonSearchbar,
  IonSplitPane,
  IonMenu,
  IonMenuToggle,
  IonRouterOutlet
} from '@ionic/angular/standalone';

export const IONIC_IMPORTS = [
  IonApp,
  IonButton,
  IonButtons,
  IonInput,
  IonItem,
  IonLabel,
  IonNote,
  IonMenuButton,
  IonList,
  IonListHeader,   // 👈 agregado aquí también
  IonContent,
  IonHeader,
  IonTitle,
  IonToolbar,
  IonCard,
  IonCardHeader,
  IonCardTitle,
  IonCardContent,
  IonIcon,
  IonGrid,
  IonRow,
  IonCol,
  IonSelect,
  IonSelectOption,
  IonSearchbar,
  IonSplitPane,
  IonMenu,
  IonMenuToggle,
  IonRouterOutlet
];
